// Videos (YouTube, SignBSL, …) attached automatically when a worksheet is uploaded,
// keyed by category and then by the worksheet's exact file name (from the
// video index supplied with each pack). Large print versions attach to
// their worksheet, so they pick up the same video.
export const VIDEO_LINKS_BY_FILE: Record<string, Record<string, string>> = {
  "Sing-Alongs": {
    "001-moonlight-bay-singalong.pdf": "https://www.youtube.com/watch?v=fTg6lw4O0w4",
    "002-pack-up-your-troubles-singalong.pdf": "https://www.youtube.com/watch?v=USTf1dkXmSE",
    "003-it-s-a-long-way-to-tipperary-singalong.pdf": "https://www.youtube.com/watch?v=y2bPUCOGDjw",
    "004-keep-the-home-fires-burning-singalong.pdf": "https://www.youtube.com/watch?v=U1Vv9a4w_wc",
    "005-if-you-were-the-only-girl-in-the-world-singalong.pdf": "https://www.youtube.com/watch?v=nyOIliG-Nb4",
    "006-ain-t-we-got-fun-singalong.pdf": "https://www.youtube.com/watch?v=Mdzk3L5kJqo",
    "007-avalon-singalong.pdf": "https://www.youtube.com/watch?v=PNDbfg7NVr8",
    "008-the-band-played-on-singalong.pdf": "https://www.youtube.com/watch?v=dLQjRpwTneg",
    "009-by-the-light-of-the-silvery-moon-singalong.pdf": "https://www.youtube.com/watch?v=3ONuZ5vEhqY",
    "010-yes-sir-that-s-my-baby-singalong.pdf": "https://www.youtube.com/watch?v=w8FUUI7oe2w",
    "011-let-me-call-you-sweetheart-singalong.pdf": "https://www.youtube.com/watch?v=nwiIOPzvTkk",
    "012-danny-boy-singalong.pdf": "https://www.youtube.com/watch?v=F4yv5AuTA9o",
    "013-school-days-singalong.pdf": "https://www.youtube.com/watch?v=kmUx6Dvxb9Q",
    "014-smiles-singalong.pdf": "https://www.youtube.com/watch?v=63Bi46xjvmE",
    "015-too-ra-loo-ra-loo-ral-singalong.pdf": "https://www.youtube.com/watch?v=G8Q3YgOSo8k",
    "016-you-made-me-love-you-singalong.pdf": "https://www.youtube.com/watch?v=Nlf0ON-Yp-U",
    "017-oh-you-beautiful-doll-singalong.pdf": "https://www.youtube.com/watch?v=vhm925fEbbI",
    "018-the-sidewalks-of-new-york-singalong.pdf": "https://www.youtube.com/watch?v=ev7ut_4SmTo",
    "019-till-we-meet-again-singalong.pdf": "https://www.youtube.com/watch?v=1H9pmi0bd3I",
    "020-i-ll-take-you-home-again-kathleen-singalong.pdf": "https://www.youtube.com/watch?v=LGbNvGtAMWg",
    "021-my-blue-heaven-singalong.pdf": "https://www.youtube.com/watch?v=GPXONLwagXk",
    "022-charleston-singalong.pdf": "https://www.youtube.com/watch?v=SGgX-eWSn4I",
    "023-april-showers-singalong.pdf": "https://www.youtube.com/watch?v=Agpro3-pWG0",
  },
  "BSL Tools": {
    "001-would-you-like-a-drink.pdf": "https://www.signbsl.com/sign/would-you-like-a-drink",
    "002-would-you-like-tea.pdf": "https://www.signbsl.com/sign/would-you-like-tea",
    "003-would-you-like-coffee.pdf": "https://www.signbsl.com/sign/would-you-like-coffee",
    "004-would-you-like-water.pdf": "https://www.signbsl.com/sign/would-you-like-water",
    "005-would-you-like-milk-sugar.pdf": "https://www.signbsl.com/sign/would-you-like-milk-sugar",
    "006-would-you-like-a-snack.pdf": "https://www.signbsl.com/sign/would-you-like-a-snack",
    "007-would-you-like-some-food.pdf": "https://www.signbsl.com/sign/would-you-like-some-food",
    "008-what-would-you-like-to-eat.pdf": "https://www.signbsl.com/sign/what-would-you-like-to-eat",
    "009-are-you-hungry.pdf": "https://www.signbsl.com/sign/are-you-hungry",
    "010-do-you-need-the-toilet.pdf": "https://www.signbsl.com/sign/do-you-need-the-toilet",
    "011-are-you-in-pain.pdf": "https://www.signbsl.com/sign/are-you-in-pain",
    "012-where-does-it-hurt.pdf": "https://www.signbsl.com/sign/where-does-it-hurt",
    "013-are-you-hurt.pdf": "https://www.signbsl.com/sign/are-you-hurt",
    "014-are-you-ok.pdf": "https://www.signbsl.com/sign/are-you-ok",
    "015-do-you-feel-ill.pdf": "https://www.signbsl.com/sign/do-you-feel-ill",
    "016-do-you-feel-sick.pdf": "https://www.signbsl.com/sign/do-you-feel-sick",
    "017-do-you-feel-better.pdf": "https://www.signbsl.com/sign/do-you-feel-better",
    "018-are-you-warm-cold.pdf": "https://www.signbsl.com/sign/are-you-warm-cold",
    "019-have-you-bumped-your-head.pdf": "https://www.signbsl.com/sign/have-you-bumped-your-head",
    "020-have-you-got-an-appointment.pdf": "https://www.signbsl.com/sign/have-you-got-an-appointment",
    "021-did-you-wash-your-hands.pdf": "https://www.signbsl.com/sign/did-you-wash-your-hands",
    "022-would-you-like-a-seat.pdf": "https://www.signbsl.com/sign/would-you-like-a-seat",
    "023-are-you-ok-to-walk.pdf": "https://www.signbsl.com/sign/are-you-ok-to-walk",
    "024-are-you-finished.pdf": "https://www.signbsl.com/sign/are-you-finished",
    "025-did-you-enjoy.pdf": "https://www.signbsl.com/sign/did-you-enjoy",
    "026-do-you-need-support.pdf": "https://www.signbsl.com/sign/do-you-need-support",
    "027-can-i-help-you.pdf": "https://www.signbsl.com/sign/can-i-help-you",
    "028-how-are-you.pdf": "https://www.signbsl.com/sign/how-are-you",
    "029-how-are-you-today.pdf": "https://www.signbsl.com/sign/how-are-you-today",
    "030-hello-how-are-you.pdf": "https://www.signbsl.com/sign/hello-how-are-you",
    "031-are-you-anxious.pdf": "https://www.signbsl.com/sign/are-you-anxious",
    "032-are-you-worried.pdf": "https://www.signbsl.com/sign/are-you-worried",
    "033-do-you-sign.pdf": "https://www.signbsl.com/sign/do-you-sign",
    "034-do-you-use-bsl.pdf": "https://www.signbsl.com/sign/do-you-use-bsl",
    "035-do-you-need-an-interpreter.pdf": "https://www.signbsl.com/sign/do-you-need-an-interpreter",
    "036-can-you-say-that-again-please.pdf": "https://www.signbsl.com/sign/can-you-say-that-again-please",
    "037-tea.pdf": "https://www.signbsl.com/sign/tea",
    "038-coffee.pdf": "https://www.signbsl.com/sign/coffee",
    "039-water.pdf": "https://www.signbsl.com/sign/water",
    "040-thirsty.pdf": "https://www.signbsl.com/sign/thirsty",
    "041-breakfast.pdf": "https://www.signbsl.com/sign/breakfast",
    "042-lunch.pdf": "https://www.signbsl.com/sign/lunch",
    "043-dinner.pdf": "https://www.signbsl.com/sign/dinner",
    "044-milk.pdf": "https://www.signbsl.com/sign/milk",
    "045-juice.pdf": "https://www.signbsl.com/sign/juice",
    "046-toilet.pdf": "https://www.signbsl.com/sign/toilet",
    "047-shower.pdf": "https://www.signbsl.com/sign/shower",
    "048-bath.pdf": "https://www.signbsl.com/sign/bath",
    "049-wash.pdf": "https://www.signbsl.com/sign/wash",
    "050-medicine.pdf": "https://www.signbsl.com/sign/medicine",
    "051-doctor.pdf": "https://www.signbsl.com/sign/doctor",
    "052-nurse.pdf": "https://www.signbsl.com/sign/nurse",
    "053-wash-hair.pdf": "https://www.signbsl.com/sign/wash-hair",
    "054-clothes.pdf": "https://www.signbsl.com/sign/clothes",
    "055-glasses.pdf": "https://www.signbsl.com/sign/glasses",
    "056-hearing-aid.pdf": "https://www.signbsl.com/sign/hearing-aid",
    "057-pain.pdf": "https://www.signbsl.com/sign/pain",
    "058-sleep.pdf": "https://www.signbsl.com/sign/sleep",
    "059-cold.pdf": "https://www.signbsl.com/sign/cold",
    "060-hot.pdf": "https://www.signbsl.com/sign/hot",
    "061-tired.pdf": "https://www.signbsl.com/sign/tired",
    "062-wheelchair.pdf": "https://www.signbsl.com/sign/wheelchair",
    "063-bed.pdf": "https://www.signbsl.com/sign/bed",
    "064-pillow.pdf": "https://www.signbsl.com/sign/pillow",
    "065-sit.pdf": "https://www.signbsl.com/sign/sit",
    "066-stand.pdf": "https://www.signbsl.com/sign/stand",
    "067-outside.pdf": "https://www.signbsl.com/sign/outside",
    "068-happy.pdf": "https://www.signbsl.com/sign/happy",
    "069-sad.pdf": "https://www.signbsl.com/sign/sad",
    "070-worried.pdf": "https://www.signbsl.com/sign/worried",
    "071-angry.pdf": "https://www.signbsl.com/sign/angry",
    "072-scared.pdf": "https://www.signbsl.com/sign/scared",
    "073-lonely.pdf": "https://www.signbsl.com/sign/lonely",
    "074-confused.pdf": "https://www.signbsl.com/sign/confused",
    "075-bored.pdf": "https://www.signbsl.com/sign/bored",
    "076-anxious.pdf": "https://www.signbsl.com/sign/anxious",
    "077-calm.pdf": "https://www.signbsl.com/sign/calm",
    "078-music.pdf": "https://www.signbsl.com/sign/music",
    "079-walk.pdf": "https://www.signbsl.com/sign/walk",
    "080-garden.pdf": "https://www.signbsl.com/sign/garden",
    "081-family.pdf": "https://www.signbsl.com/sign/family",
    "082-help.pdf": "https://www.signbsl.com/sign/help",
    "083-television.pdf": "https://www.signbsl.com/sign/television",
    "084-read.pdf": "https://www.signbsl.com/sign/read",
    "085-book.pdf": "https://www.signbsl.com/sign/book",
    "086-bingo.pdf": "https://www.signbsl.com/sign/bingo",
    "087-exercise.pdf": "https://www.signbsl.com/sign/exercise",
    "088-sing.pdf": "https://www.signbsl.com/sign/sing",
    "089-visitor.pdf": "https://www.signbsl.com/sign/visitor",
    "090-telephone.pdf": "https://www.signbsl.com/sign/telephone",
  },
};

export function videoUrlFor(category: string, fileName: string): string | null {
  return VIDEO_LINKS_BY_FILE[category]?.[fileName] ?? null;
}
